Table users {
  id SERIAL [pk, increment]
  created_at TIMESTAMP
  updated_at TIMESTAMP
  username VARCHAR(30)
}

Table posts {
  id SERIAL [pk, increment]
  created_at TIMESTAMP
  updated_at TIMESTAMP
  url VARCHAR(200)
  user_id INTEGER [ref: > users.id]
  caption VARCHAR(240)
  lat REAL
  lng REAL
}

Table comments {
  id SERIAL [pk, increment]
  created_at TIMESTAMP
  updated_at TIMESTAMP
  contents VARCHAR(240)
  user_id INTEGER [ref: > users.id]
  post_id INTEGER [ref: > posts.id]
}

Table likes {
  id SERIAL [pk, increment]
  created_at TIMESTAMP
  contents VARCHAR(240)
  user_id INTEGER [ref: > users.id]
  comment_id INTEGER [ref: > comment.id]
  post_id INTEGER [ref: > posts.id]
}


Table caption_tags {
  id SERIAL [pk, increment]
  created_at TIMESTAMP

  user_id INTEGER [ref: > users.id]
  post_id INTEGER [ref: > posts.id]
}

Table photo_tags {
  id SERIAL [pk, increment]
  created_at TIMESTAMP
  updated_at TIMESTAMP

  user_id INTEGER [ref: > users.id]
  post_id INTEGER [ref: > posts.id]

  x INTEGER
  y INTEGER
}

